Ttree:
  Embedly:
    enableResponseCache: TRUE
    logApiRequest: TRUE
    apiKey: 'your-own-api-key'

TYPO3:
  TypoScript:
    defaultContext:
      Embedly: 'Ttree\Embedly\Eel\Helper\EmbedlyHelper'

  Neos:
    typoScript:
      autoInclude:
        'Ttree.Embedly': TRUE

    userInterface:
      translation:
        autoInclude:
          'Ttree.Embedly': ['NodeTypes/*']
